#!/bin/sh
# postrm script for emailclaw
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappear-postrm> `disappear' <overwriter> <new-version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    purge)
        # Clean up unprivileged accounts and data directories (only takes effect when the user explicitly executes apt purge)
        if id -u emailclaw >/dev/null 2>&1; then
            echo "=========================================================="
            echo " [emailclaw] Cleaning up persistent data directory and system account..."
            userdel -r emailclaw || true
            rm -rf /home/emailclaw || true
            echo " [emailclaw] Data cleanup completed."
            echo "=========================================================="
        fi
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
