/*
 * The MIT License (MIT)
 * Copyright © 2026 the original author or authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package ai.emailclaw.emailclaw.model;

/**
 * File modification diff record.
 *
 * <p>Records line-level diff information generated by a file write or edit operation, including added lines, deleted lines, and diff summary,
 * for ChatView to present to the user as an expandable diff panel in WebView.
 */
public class FileDiffRecord {

    /** The modified file path. */
    private final String filePath;

    /** The number of added lines. */
    private final int linesAdded;

    /** The number of deleted lines. */
    private final int linesDeleted;

    /** The complete text in unified diff format. */
    private final String unifiedDiff;

    /** Whether it is a new file (did not exist before). */
    private final boolean isNewFile;

    /**
     * Construct a file modification diff record.
     *
     * @param filePath     file path
     * @param linesAdded   added lines count
     * @param linesDeleted deleted lines count
     * @param unifiedDiff  unified diff text
     * @param isNewFile    whether it is a new file
     */
    public FileDiffRecord(
            String filePath,
            int linesAdded,
            int linesDeleted,
            String unifiedDiff,
            boolean isNewFile) {
        this.filePath = filePath == null ? "" : filePath;
        this.linesAdded = linesAdded;
        this.linesDeleted = linesDeleted;
        this.unifiedDiff = unifiedDiff == null ? "" : unifiedDiff;
        this.isNewFile = isNewFile;
    }

    /**
     * Get the modified file path.
     *
     * @return file path
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Get the number of added lines.
     *
     * @return added lines count
     */
    public int getLinesAdded() {
        return linesAdded;
    }

    /**
     * Get the number of deleted lines.
     *
     * @return deleted lines count
     */
    public int getLinesDeleted() {
        return linesDeleted;
    }

    /**
     * Get the complete text in unified diff format.
     *
     * @return unified diff text
     */
    public String getUnifiedDiff() {
        return unifiedDiff;
    }

    /**
     * Determine whether it is a new file (did not exist before).
     *
     * @return whether it is a new file
     */
    public boolean isNewFile() {
        return isNewFile;
    }

    /**
     * Generate a concise diff summary line to embed in the tool result.
     *
     * <p>Format example: {@code [DIFF] +12 -3 lines | path/to/File.java}
     *
     * @return single-line summary string
     */
    public String summary() {
        StringBuilder sb = new StringBuilder();
        sb.append("[DIFF] ");
        if (isNewFile) {
            sb.append("(new file) ");
        }
        sb.append('+').append(linesAdded).append(' ');
        sb.append('-').append(linesDeleted).append(" lines | ");
        sb.append(filePath);
        return sb.toString();
    }

    /**
     * Generate a complete markup block containing the diff summary and unified diff.
     *
     * <p>Format: wrapped in {@code <<<FILE_DIFF>>>} and {@code <<<END_FILE_DIFF>>>} tags,
     * for ChatView to parse and render as an expandable diff panel.
     *
     * @return complete markup text
     */
    public String toMarkup() {
        StringBuilder sb = new StringBuilder();
        sb.append("\n<<<FILE_DIFF>>>\n");
        sb.append("FILE: ").append(filePath).append('\n');
        sb.append("ADDED: ").append(linesAdded).append('\n');
        sb.append("DELETED: ").append(linesDeleted).append('\n');
        sb.append("NEW_FILE: ").append(isNewFile).append('\n');
        sb.append("---\n");
        sb.append(unifiedDiff);
        sb.append("\n<<<END_FILE_DIFF>>>\n");
        return sb.toString();
    }
}
