/*
 * The MIT License (MIT)
 * Copyright © 2026 the original author or authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
package ai.emailclaw.emailclaw.plugin;

import ai.emailclaw.emailclaw.model.ChatMessagePart;
import java.util.List;
import java.util.Map;

/**
 * Main entry point SPI interface for plugins.
 * All backend plugins need to implement this interface and register it in META-INF/services/ai.emailclaw.emailclaw.plugin.EmailclawPlugin,
 * or point entry_point in plugin.json to its fully qualified class name.
 */
public interface EmailclawPlugin {

    /**
     * Called when the plugin is loaded, custom objects can be registered to the registry here.
     *
     * @param registry Global plugin registry
     */
    void register(PluginRegistry registry);

    /**
     * Called when the plugin is unloaded or the system is shut down.
     */
    default void onUnload() {}

    /**
     * Plugin unique identifier.
     */
    default String id() {
        return getClass().getSimpleName();
    }

    /**
     * Human-readable display name.
     */
    default String displayName() {
        return id();
    }

    /**
     * Declares the configuration item schema required by this plugin.
     */
    default List<ConfigFieldDescriptor> configSchema() {
        return List.of();
    }

    /**
     * Initializes the plugin. The framework calls this method immediately after discovering the plugin to inject a unified context.
     */
    default void initialize(PluginContext context) {}

    /**
     * Starts the plugin. Establishes external connections, starts polling, etc.
     */
    default void start() {}

    /**
     * Stops the plugin. Releases external connections, stops background threads.
     */
    default void stop() {}

    /**
     * Sends the Agent's reply to the recipient of the corresponding session via the channel.
     *
     * <p>The default implementation is a no-op, to be overridden by each channel plugin as needed.
     * For example, the Emailclaw channel will find the email address associated with the session and send an SMTP email,
     * while Console/Web channels usually do not need any action (the user has already seen the reply on the frontend).
     *
     * @param sessionId Target session ID
     * @param content   Reply text content generated by the Agent
     */
    default void replyToSession(String sessionId, String content) {}

    /**
     * Determines whether this channel plugin supports real-time stream chunk delivery.
     *
     * <p>For non-interactive or batch protocols (such as SMTP email delivery), streaming
     * intermediate tokens or chunks is usually not supported or desirable, so this returns {@code false}.
     * Interactive channels (e.g., Console, WebSocket, DingTalk/Feishu card streaming) can override
     * this to return {@code true}.
     *
     * @return {@code true} if streaming delivery is supported, {@code false} otherwise.
     */
    default boolean supportsStreaming() {
        return false;
    }

    /**
     * Streams an incremental content part of the Agent's reply to the recipient of the session.
     *
     * <p>The default implementation is a no-op. Subclasses that support streaming delivery should
     * override this method to forward incremental deltas to the client or channel platform.
     *
     * @param sessionId Target session ID
     * @param part      Content part containing incremental text or metadata
     * @param startsNew Whether this chunk initiates a new block
     */
    default void streamPartToSession(String sessionId, ChatMessagePart part, boolean startsNew) {}

    /**
     * Notifies the channel that the stream delivery for the session has completed.
     *
     * <p>The default implementation is a no-op. Subclasses that support streaming delivery can
     * perform finalization or commit operations here.
     *
     * @param sessionId   Target session ID
     * @param fullContent The complete text content produced by the Agent
     */
    default void onStreamCompleted(String sessionId, String fullContent) {}

    /**
     * Destroys the plugin, releasing all resources.
     */
    default void destroy() {
        stop();
        onUnload();
    }

    /**
     * Gets a snapshot of the current running status.
     */
    default PluginStatus status() {
        return PluginStatus.registered();
    }

    /**
     * Normalizes the plugin configuration. Called after configuration is loaded and before it is saved.
     * Plugins can perform operations here such as configuration structure compatibility, clearing redundant sensitive fields (like not persisting server parameters for preset emails).
     *
     * @param pluginConfig The original configuration Map belonging to this plugin
     * @return Returns true if the configuration content was modified by the plugin, prompting the caller to trigger a storage update.
     */
    default boolean normalizeConfig(Map<String, Object> pluginConfig) {
        return false;
    }
}
